### ISSUE TITLE
Mix language target error

### ISSUE THREAD

**Issue by sebastien-de-saint-florent** [PromiseKit/EZiOS7#2]
Hello,

I have an issue when using EZiOS7 in a mix language project. When I import both PromiseKit.h and the project swift header file in a .m file : 
```
#import "PromiseKit.h"
#import "TestPromiseKit-Swift.h"
```
I have the following compilation error : 
```
/Users/someusername/Library/Developer/Xcode/DerivedData/TestPromiseKit-ebtizuxtjopfalcaqhmhvjcmhorl/Build/Intermediates/TestPromiseKit.build/Debug-iphonesimulator/TestPromiseKit.build/DerivedSources/TestPromiseKit-Swift.h:96:1: Duplicate interface definition for class 'PMKPromise'
```
Thanks,

**Comment by mxcl** [comment]
Does inverting the import order fix it? Ie:

```
#import "TestPromiseKit-Swift.h"
#import "PromiseKit.h"
```

**Comment by mxcl** [comment]
Just tested, it doesn’t fix it. Let me figure out a fix.

**Comment by mxcl** [comment]
A workaround for now is to replace:

```objc
__attribute__((objc_runtime_name("PMKAnyPromise")))
__attribute__((objc_subclassing_restricted))
@interface PMKPromise : NSObject
@property (nonatomic, readonly) BOOL pending;
@property (nonatomic, readonly) BOOL resolved;
@property (nonatomic, readonly) BOOL fulfilled;
@property (nonatomic, readonly) BOOL rejected;
@end

@compatibility_alias AnyPromise PMKPromise;
```

With:

```
#define PMKPromise AnyPromise
```

And now you *must* import your `project-Swift-h` header first always.

This sucks, I'll see if I can figure out a solution. I don't think I can though.

**Comment by mxcl** [comment]
Note currently you must include the `project-Swift-h` **BEFORE** `PromiseKit.h` or you get another compile error. I'll try to fix that too.

**Comment by sebastien-de-saint-florent** [comment]
Yeah, It's working now.

Many thanks
