### ISSUE TITLE
Categories uses methods only available in iOS 8

### ISSUE THREAD

**Issue by fmaylinch** [PromiseKit/EZiOS7#4]
I would like to use PromiseKit 2 on iOS7 but I think the Categories code is calling iOS8 methods.

For example, [CLLocationManager+AnyPromise.m:57](https://github.com/mxcl/PromiseKit/blob/master/Categories/CoreLocation/CLLocationManager%2BAnyPromise.m#L57) calls `requestWhenInUseAuthorization`, which is available from iOS8.

**Comment by mxcl** [comment]
Can you open this bug report on PromiseKit itself please.

**Comment by mxcl** [comment]
I cannot test this on my El Capitan machine so I need to check out my iOS 7 test project on another machine. I'll push if it is all good.
