### ISSUE TITLE
Swift 2.0 support?

### ISSUE THREAD

**Issue by sebastien-de-saint-florent** [PromiseKit/EZiOS7#5]
Hi,

I'm preparing the migration of my project to swift 2.0. How can I generate EZiOS7 files for swift 2.0 from the main repo?

Thanks,

**Comment by mxcl** [comment]
K, well clone this project. Then:

```bash
cd .checkout
git pull origin swift-2.0-beta4
cd ..
ruby .admin/update.rb
```

Should do it. Let me know if it works.

**Comment by mxcl** [comment]
Still, I'm not sure you can use Swift 2.0 and target iOS 7 at this point. If you aren’t targeting iOS 7 I recommend CocoaPods, Carthage or cloning PromiseKit and either building it as part of your project or building the swift-2.0 binary and using that as a framework.

When not used as a framework the access modifiers are wrong and there are a few other subtle usage issues. But nothing too major, so do whatever you prefer.

**Comment by sebastien-de-saint-florent** [comment]
Hi,

I've compiled the project using .admin/update.rb. I've removed '.checkout/Sources/PMKPromise.h' file from the script since this file it's not in swift-2.0-beta4.
I still have an issue : when used in a mix language project, PromiseKit.h raise a lot of compilation errors like this one : 
error: cannot find interface declaration for 'PMKPromise'; did you mean 'PMKAnyPromise'?

Is it related somehow to issue #2 ?

Regards

**Comment by mxcl** [comment]
K, I'll look into it, thanks.

**Comment by mxcl** [comment]
worksforme.

Can you provide a screenshot of the errors?

Please also check you have read the README completely, as there are a variety of extra steps you must make to use EZiOS7.

**Comment by mxcl** [comment]
I've pushed a swift-2.0 branch that works. Thanks for the report and let me know if you have any other problems.

**Comment by sebastien-de-saint-florent** [comment]
Hello, 

Thank you very much. It does the trick :)

By the way I encountered a weird error with some comments included in the source file:
```
      - Warning: You may only call this method on the main thread.
```
This comment generate a \Warning in myproject-swift.h header (which don't compile). Removing '-Warning' fix the issue. 

Regards,

**Comment by mxcl** [comment]
Yes I saw that too. Presumably is a bug in the script.
